name: Generate Android Folder
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Generate Native Android Folder
        run: npx expo prebuild --platform android --template blank

      - name: Upload Android Folder as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-android-folder
          path: android/
